### PR TITLE
Enh: re-enable the heartbeat thread

### PR DESCRIPTION
**Pull request by gst**
very usefull if you want to keep a connection open (through some FW or LB, or anything) but without having to worry about it at all (tcp session timeout, etc..).

### CODE REVIEW

**Comment by veegee** [comment]
Sure, I can enable it. I'm contemplating whether or not to disable the inline heartbeats that `drain_events()` sends automatically.

**Comment by gst** [comment]
I had the same question..

**Comment by gst** [comment]
Probably we should not send those heartbeats in drain_events() if the heartbeat thread has been enabled ? and otherwise still do it ?

wdyt ?

**Comment by veegee** [comment]
I would think simply removing it from `drain_events()` is better to keep things simple. Otherwise, it may lead to confusion when connections randomly close if the user forgets to send a heartbeat manually in a long running task.

**Comment by gst** [comment]
you are right, simpler, simpler and simpler is (almost always) better :)

**Comment by gst** [comment]
there.. I had some error when running tox(3) on my side.. not sure if related..

**Comment by gst** [comment]
rebased and cleaned.

@veegee 
wdyt ?

**Comment by gst** [comment]
NB: I noticed the `Connection.is_alive()`  method also sends an heartbeat under the hood..
but I think / am mostly sure it's all safe to keep it like that.

Now, thinking again to the heartbeat thread itself.. would you find it good to add an optional callback parameter to the Connection \_\_init\_\_, so that the heartbeat thread would execute that callback once it sees the connection gone (or just that no heartbeat coming from the server as expected) ? 
Could be useful, don't you think  ?..

And finally: there is an obvious mistake in my PR.. correcting ..

**Comment by veegee** [comment]
Ok, I ran some tests, and it looks like it's good to merge.

**Pull request merged**
